<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StandarAntopometriPerempuanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => '1',
                'usia_bulan' => 0,
                'tb_sd_minus_3' => 43.6,
                'tb_sd_minus_2' => 45.4,
                'tb_sd_minus_1' => 47.3,
                'tb_sd_median' => 49.1,
                'tb_sd_plus_1' => 51.0,
                'tb_sd_plus_2' => 52.9,
                'tb_sd_plus_3' => 54.7,
            ],
            [
                'id' => '2',
                'usia_bulan' => 1,
                'tb_sd_minus_3' => 47.8,
                'tb_sd_minus_2' => 49.8,
                'tb_sd_minus_1' => 51.7,
                'tb_sd_median' => 53.7,
                'tb_sd_plus_1' => 55.6,
                'tb_sd_plus_2' => 57.6,
                'tb_sd_plus_3' => 59.5,
            ],
            [
                'id' => '3',
                'usia_bulan' => 2,
                'tb_sd_minus_3' => 51.0,
                'tb_sd_minus_2' => 53.0,
                'tb_sd_minus_1' => 55.0,
                'tb_sd_median' => 57.1,
                'tb_sd_plus_1' => 59.1,
                'tb_sd_plus_2' => 61.1,
                'tb_sd_plus_3' => 63.2,
            ],
            [
                'id' => '4',
                'usia_bulan' => 3,
                'tb_sd_minus_3' => 53.5,
                'tb_sd_minus_2' => 55.6,
                'tb_sd_minus_1' => 57.7,
                'tb_sd_median' => 59.8,
                'tb_sd_plus_1' => 61.9,
                'tb_sd_plus_2' => 64.0,
                'tb_sd_plus_3' => 66.1,
            ],
            [
                'id' => '5',
                'usia_bulan' => 4,
                'tb_sd_minus_3' => 55.6,
                'tb_sd_minus_2' => 57.8,
                'tb_sd_minus_1' => 59.9,
                'tb_sd_median' => 62.1,
                'tb_sd_plus_1' => 64.3,
                'tb_sd_plus_2' => 66.4,
                'tb_sd_plus_3' => 68.6,
            ],
            [
                'id' => '6',
                'usia_bulan' => 5,
                'tb_sd_minus_3' => 57.4,
                'tb_sd_minus_2' => 59.6,
                'tb_sd_minus_1' => 61.8,
                'tb_sd_median' => 64.0,
                'tb_sd_plus_1' => 66.2,
                'tb_sd_plus_2' => 68.5,
                'tb_sd_plus_3' => 70.7,
            ],
            [
                'id' => '7',
                'usia_bulan' => 6,
                'tb_sd_minus_3' => 58.9,
                'tb_sd_minus_2' => 61.2,
                'tb_sd_minus_1' => 63.5,
                'tb_sd_median' => 65.7,
                'tb_sd_plus_1' => 68.0,
                'tb_sd_plus_2' => 70.3,
                'tb_sd_plus_3' => 72.5,
            ],
            [
                'id' => '8',
                'usia_bulan' => 7,
                'tb_sd_minus_3' => 60.3,
                'tb_sd_minus_2' => 62.7,
                'tb_sd_minus_1' => 65.0,
                'tb_sd_median' => 67.3,
                'tb_sd_plus_1' => 69.6,
                'tb_sd_plus_2' => 71.9,
                'tb_sd_plus_3' => 74.2,
            ],
            [
                'id' => '9',
                'usia_bulan' => 8,
                'tb_sd_minus_3' => 61.7,
                'tb_sd_minus_2' => 64.0,
                'tb_sd_minus_1' => 66.4,
                'tb_sd_median' => 68.7,
                'tb_sd_plus_1' => 71.1,
                'tb_sd_plus_2' => 73.5,
                'tb_sd_plus_3' => 75.8,
            ],
            [
                'id' => '10',
                'usia_bulan' => 9,
                'tb_sd_minus_3' => 62.9,
                'tb_sd_minus_2' => 65.3,
                'tb_sd_minus_1' => 67.7,
                'tb_sd_median' => 70.1,
                'tb_sd_plus_1' => 72.6,
                'tb_sd_plus_2' => 75.0,
                'tb_sd_plus_3' => 77.4,
            ],
            [
                'id' => '11',
                'usia_bulan' => 10,
                'tb_sd_minus_3' => 64.1,
                'tb_sd_minus_2' => 66.5,
                'tb_sd_minus_1' => 69.0,
                'tb_sd_median' => 71.5,
                'tb_sd_plus_1' => 73.9,
                'tb_sd_plus_2' => 76.4,
                'tb_sd_plus_3' => 78.9,
            ],
            [
                'id' => '12',
                'usia_bulan' => 11,
                'tb_sd_minus_3' => 65.2,
                'tb_sd_minus_2' => 67.7,
                'tb_sd_minus_1' => 70.3,
                'tb_sd_median' => 72.8,
                'tb_sd_plus_1' => 75.3,
                'tb_sd_plus_2' => 77.8,
                'tb_sd_plus_3' => 80.3,
            ],
            [
                'id' => '13',
                'usia_bulan' => 12,
                'tb_sd_minus_3' => 66.3,
                'tb_sd_minus_2' => 68.9,
                'tb_sd_minus_1' => 71.4,
                'tb_sd_median' => 74.0,
                'tb_sd_plus_1' => 76.6,
                'tb_sd_plus_2' => 79.2,
                'tb_sd_plus_3' => 81.7,
            ],
            [
                'id' => '14',
                'usia_bulan' => 13,
                'tb_sd_minus_3' => 67.3,
                'tb_sd_minus_2' => 70.0,
                'tb_sd_minus_1' => 72.6,
                'tb_sd_median' => 75.2,
                'tb_sd_plus_1' => 77.8,
                'tb_sd_plus_2' => 80.5,
                'tb_sd_plus_3' => 83.1,
            ],
            [
                'id' => '15',
                'usia_bulan' => 14,
                'tb_sd_minus_3' => 68.3,
                'tb_sd_minus_2' => 71.0,
                'tb_sd_minus_1' => 73.7,
                'tb_sd_median' => 76.4,
                'tb_sd_plus_1' => 79.1,
                'tb_sd_plus_2' => 81.7,
                'tb_sd_plus_3' => 84.4,
            ],
            [
                'id' => '16',
                'usia_bulan' => 15,
                'tb_sd_minus_3' => 69.3,
                'tb_sd_minus_2' => 72.0,
                'tb_sd_minus_1' => 74.8,
                'tb_sd_median' => 77.5,
                'tb_sd_plus_1' => 80.2,
                'tb_sd_plus_2' => 83.0,
                'tb_sd_plus_3' => 85.7,
            ],
            [
                'id' => '17',
                'usia_bulan' => 16,
                'tb_sd_minus_3' => 70.2,
                'tb_sd_minus_2' => 73.0,
                'tb_sd_minus_1' => 75.8,
                'tb_sd_median' => 78.6,
                'tb_sd_plus_1' => 81.4,
                'tb_sd_plus_2' => 84.2,
                'tb_sd_plus_3' => 87.0,
            ],
            [
                'id' => '18',
                'usia_bulan' => 17,
                'tb_sd_minus_3' => 71.1,
                'tb_sd_minus_2' => 73.9,
                'tb_sd_minus_1' => 76.8,
                'tb_sd_median' => 79.7,
                'tb_sd_plus_1' => 82.5,
                'tb_sd_plus_2' => 85.4,
                'tb_sd_plus_3' => 88.2,
            ],
            [
                'id' => '19',
                'usia_bulan' => 18,
                'tb_sd_minus_3' => 72.0,
                'tb_sd_minus_2' => 74.8,
                'tb_sd_minus_1' => 77.8,
                'tb_sd_median' => 80.7,
                'tb_sd_plus_1' => 83.6,
                'tb_sd_plus_2' => 86.5,
                'tb_sd_plus_3' => 89.4,
            ],
            [
                'id' => '20',
                'usia_bulan' => 19,
                'tb_sd_minus_3' => 72.8,
                'tb_sd_minus_2' => 75.7,
                'tb_sd_minus_1' => 78.8,
                'tb_sd_median' => 81.7,
                'tb_sd_plus_1' => 84.7,
                'tb_sd_plus_2' => 87.6,
                'tb_sd_plus_3' => 90.6,
            ],
            [
                'id' => '21',
                'usia_bulan' => 20,
                'tb_sd_minus_3' => 73.7,
                'tb_sd_minus_2' => 76.6,
                'tb_sd_minus_1' => 79.7,
                'tb_sd_median' => 82.7,
                'tb_sd_plus_1' => 85.7,
                'tb_sd_plus_2' => 88.7,
                'tb_sd_plus_3' => 91.7,
            ],
            [
                'id' => '22',
                'usia_bulan' => 21,
                'tb_sd_minus_3' => 74.5,
                'tb_sd_minus_2' => 77.4,
                'tb_sd_minus_1' => 80.6,
                'tb_sd_median' => 83.7,
                'tb_sd_plus_1' => 86.7,
                'tb_sd_plus_2' => 89.8,
                'tb_sd_plus_3' => 92.9,
            ],
            [
                'id' => '23',
                'usia_bulan' => 22,
                'tb_sd_minus_3' => 75.2,
                'tb_sd_minus_2' => 78.3,
                'tb_sd_minus_1' => 81.5,
                'tb_sd_median' => 84.6,
                'tb_sd_plus_1' => 87.7,
                'tb_sd_plus_2' => 90.8,
                'tb_sd_plus_3' => 94.0,
            ],
            [
                'id' => '24',
                'usia_bulan' => 23,
                'tb_sd_minus_3' => 76.0,
                'tb_sd_minus_2' => 79.1,
                'tb_sd_minus_1' => 82.3,
                'tb_sd_median' => 85.5,
                'tb_sd_plus_1' => 88.7,
                'tb_sd_plus_2' => 91.9,
                'tb_sd_plus_3' => 95.0,
            ],
            [
                'id' => '25',
                'usia_bulan' => 24,
                'tb_sd_minus_3' => 76.7,
                'tb_sd_minus_2' => 79.8,
                'tb_sd_minus_1' => 83.2,
                'tb_sd_median' => 86.4,
                'tb_sd_plus_1' => 89.6,
                'tb_sd_plus_2' => 92.9,
                'tb_sd_plus_3' => 96.1,
            ],
            [
                'id' => '26',
                'usia_bulan' => 25,
                'tb_sd_minus_3' => 77.5,
                'tb_sd_minus_2' => 80.6,
                'tb_sd_minus_1' => 84.0,
                'tb_sd_median' => 87.3,
                'tb_sd_plus_1' => 90.6,
                'tb_sd_plus_2' => 93.8,
                'tb_sd_plus_3' => 97.1,
            ],
            [
                'id' => '27',
                'usia_bulan' => 26,
                'tb_sd_minus_3' => 78.1,
                'tb_sd_minus_2' => 81.4,
                'tb_sd_minus_1' => 84.8,
                'tb_sd_median' => 88.2,
                'tb_sd_plus_1' => 91.5,
                'tb_sd_plus_2' => 94.8,
                'tb_sd_plus_3' => 98.1,
            ],
            [
                'id' => '28',
                'usia_bulan' => 27,
                'tb_sd_minus_3' => 78.8,
                'tb_sd_minus_2' => 82.1,
                'tb_sd_minus_1' => 85.6,
                'tb_sd_median' => 89.0,
                'tb_sd_plus_1' => 92.4,
                'tb_sd_plus_2' => 95.7,
                'tb_sd_plus_3' => 99.1,
            ],
            [
                'id' => '29',
                'usia_bulan' => 28,
                'tb_sd_minus_3' => 79.5,
                'tb_sd_minus_2' => 82.8,
                'tb_sd_minus_1' => 86.4,
                'tb_sd_median' => 89.9,
                'tb_sd_plus_1' => 93.3,
                'tb_sd_plus_2' => 96.7,
                'tb_sd_plus_3' => 100.1,
            ],
            [
                'id' => '30',
                'usia_bulan' => 29,
                'tb_sd_minus_3' => 80.1,
                'tb_sd_minus_2' => 83.5,
                'tb_sd_minus_1' => 87.1,
                'tb_sd_median' => 90.7,
                'tb_sd_plus_1' => 94.2,
                'tb_sd_plus_2' => 97.6,
                'tb_sd_plus_3' => 101.0,
            ],
            [
                'id' => '31',
                'usia_bulan' => 30,
                'tb_sd_minus_3' => 80.7,
                'tb_sd_minus_2' => 84.2,
                'tb_sd_minus_1' => 87.8,
                'tb_sd_median' => 91.4,
                'tb_sd_plus_1' => 95.0,
                'tb_sd_plus_2' => 98.5,
                'tb_sd_plus_3' => 102.0,
            ],
            [
                'id' => '32',
                'usia_bulan' => 31,
                'tb_sd_minus_3' => 81.3,
                'tb_sd_minus_2' => 84.9,
                'tb_sd_minus_1' => 88.5,
                'tb_sd_median' => 92.2,
                'tb_sd_plus_1' => 95.8,
                'tb_sd_plus_2' => 99.4,
                'tb_sd_plus_3' => 103.0,
            ],
            [
                'id' => '33',
                'usia_bulan' => 32,
                'tb_sd_minus_3' => 81.9,
                'tb_sd_minus_2' => 85.5,
                'tb_sd_minus_1' => 89.2,
                'tb_sd_median' => 92.9,
                'tb_sd_plus_1' => 96.6,
                'tb_sd_plus_2' => 100.3,
                'tb_sd_plus_3' => 103.9,
            ],
            [
                'id' => '34',
                'usia_bulan' => 33,
                'tb_sd_minus_3' => 82.5,
                'tb_sd_minus_2' => 86.2,
                'tb_sd_minus_1' => 89.9,
                'tb_sd_median' => 93.6,
                'tb_sd_plus_1' => 97.4,
                'tb_sd_plus_2' => 101.1,
                'tb_sd_plus_3' => 104.8,
            ],
            [
                'id' => '35',
                'usia_bulan' => 34,
                'tb_sd_minus_3' => 83.1,
                'tb_sd_minus_2' => 86.8,
                'tb_sd_minus_1' => 90.6,
                'tb_sd_median' => 94.4,
                'tb_sd_plus_1' => 98.1,
                'tb_sd_plus_2' => 101.9,
                'tb_sd_plus_3' => 105.7,
            ],
            [
                'id' => '36',
                'usia_bulan' => 35,
                'tb_sd_minus_3' => 83.6,
                'tb_sd_minus_2' => 87.4,
                'tb_sd_minus_1' => 91.2,
                'tb_sd_median' => 95.1,
                'tb_sd_plus_1' => 98.9,
                'tb_sd_plus_2' => 102.7,
                'tb_sd_plus_3' => 106.5,
            ],
            [
                'id' => '37',
                'usia_bulan' => 36,
                'tb_sd_minus_3' => 84.2,
                'tb_sd_minus_2' => 88.0,
                'tb_sd_minus_1' => 91.9,
                'tb_sd_median' => 95.7,
                'tb_sd_plus_1' => 99.6,
                'tb_sd_plus_2' => 103.4,
                'tb_sd_plus_3' => 107.3,
            ],
            [
                'id' => '38',
                'usia_bulan' => 37,
                'tb_sd_minus_3' => 84.7,
                'tb_sd_minus_2' => 88.6,
                'tb_sd_minus_1' => 92.5,
                'tb_sd_median' => 96.4,
                'tb_sd_plus_1' => 100.3,
                'tb_sd_plus_2' => 104.2,
                'tb_sd_plus_3' => 108.1,
            ],
            [
                'id' => '39',
                'usia_bulan' => 38,
                'tb_sd_minus_3' => 85.3,
                'tb_sd_minus_2' => 89.2,
                'tb_sd_minus_1' => 93.1,
                'tb_sd_median' => 97.1,
                'tb_sd_plus_1' => 101.0,
                'tb_sd_plus_2' => 104.9,
                'tb_sd_plus_3' => 108.9,
            ],
            [
                'id' => '40',
                'usia_bulan' => 39,
                'tb_sd_minus_3' => 85.8,
                'tb_sd_minus_2' => 89.8,
                'tb_sd_minus_1' => 93.8,
                'tb_sd_median' => 97.7,
                'tb_sd_plus_1' => 101.7,
                'tb_sd_plus_2' => 105.7,
                'tb_sd_plus_3' => 109.7,
            ],
            [
                'id' => '41',
                'usia_bulan' => 40,
                'tb_sd_minus_3' => 86.3,
                'tb_sd_minus_2' => 90.4,
                'tb_sd_minus_1' => 94.4,
                'tb_sd_median' => 98.4,
                'tb_sd_plus_1' => 102.4,
                'tb_sd_plus_2' => 106.4,
                'tb_sd_plus_3' => 110.5,
            ],
            [
                'id' => '42',
                'usia_bulan' => 41,
                'tb_sd_minus_3' => 86.8,
                'tb_sd_minus_2' => 90.9,
                'tb_sd_minus_1' => 95.0,
                'tb_sd_median' => 99.0,
                'tb_sd_plus_1' => 103.1,
                'tb_sd_plus_2' => 107.2,
                'tb_sd_plus_3' => 111.2,
            ],
            [
                'id' => '43',
                'usia_bulan' => 42,
                'tb_sd_minus_3' => 87.4,
                'tb_sd_minus_2' => 91.5,
                'tb_sd_minus_1' => 95.6,
                'tb_sd_median' => 99.7,
                'tb_sd_plus_1' => 103.8,
                'tb_sd_plus_2' => 107.9,
                'tb_sd_plus_3' => 112.0,
            ],
            [
                'id' => '44',
                'usia_bulan' => 43,
                'tb_sd_minus_3' => 87.9,
                'tb_sd_minus_2' => 92.0,
                'tb_sd_minus_1' => 96.2,
                'tb_sd_median' => 100.3,
                'tb_sd_plus_1' => 104.5,
                'tb_sd_plus_2' => 108.6,
                'tb_sd_plus_3' => 112.7,
            ],
            [
                'id' => '45',
                'usia_bulan' => 44,
                'tb_sd_minus_3' => 88.4,
                'tb_sd_minus_2' => 92.6,
                'tb_sd_minus_1' => 96.8,
                'tb_sd_median' => 101.0,
                'tb_sd_plus_1' => 105.1,
                'tb_sd_plus_2' => 109.3,
                'tb_sd_plus_3' => 113.5,
            ],
            [
                'id' => '46',
                'usia_bulan' => 45,
                'tb_sd_minus_3' => 89.0,
                'tb_sd_minus_2' => 93.1,
                'tb_sd_minus_1' => 97.4,
                'tb_sd_median' => 101.6,
                'tb_sd_plus_1' => 105.8,
                'tb_sd_plus_2' => 110.0,
                'tb_sd_plus_3' => 114.2,
            ],
            [
                'id' => '47',
                'usia_bulan' => 46,
                'tb_sd_minus_3' => 89.5,
                'tb_sd_minus_2' => 93.7,
                'tb_sd_minus_1' => 98.0,
                'tb_sd_median' => 102.2,
                'tb_sd_plus_1' => 106.4,
                'tb_sd_plus_2' => 110.7,
                'tb_sd_plus_3' => 114.9,
            ],
            [
                'id' => '48',
                'usia_bulan' => 47,
                'tb_sd_minus_3' => 90.0,
                'tb_sd_minus_2' => 94.2,
                'tb_sd_minus_1' => 98.5,
                'tb_sd_median' => 102.8,
                'tb_sd_plus_1' => 107.1,
                'tb_sd_plus_2' => 111.3,
                'tb_sd_plus_3' => 115.6,
            ],
            [
                'id' => '49',
                'usia_bulan' => 48,
                'tb_sd_minus_3' => 90.5,
                'tb_sd_minus_2' => 94.7,
                'tb_sd_minus_1' => 99.1,
                'tb_sd_median' => 103.4,
                'tb_sd_plus_1' => 107.7,
                'tb_sd_plus_2' => 112.0,
                'tb_sd_plus_3' => 116.3,
            ],
            [
                'id' => '50',
                'usia_bulan' => 49,
                'tb_sd_minus_3' => 91.0,
                'tb_sd_minus_2' => 95.2,
                'tb_sd_minus_1' => 99.6,
                'tb_sd_median' => 104.0,
                'tb_sd_plus_1' => 108.3,
                'tb_sd_plus_2' => 112.7,
                'tb_sd_plus_3' => 117.0,
            ],
            [
                'id' => '51',
                'usia_bulan' => 50,
                'tb_sd_minus_3' => 91.4,
                'tb_sd_minus_2' => 95.7,
                'tb_sd_minus_1' => 100.1,
                'tb_sd_median' => 104.5,
                'tb_sd_plus_1' => 108.9,
                'tb_sd_plus_2' => 113.3,
                'tb_sd_plus_3' => 117.7,
            ],
            [
                'id' => '52',
                'usia_bulan' => 51,
                'tb_sd_minus_3' => 91.9,
                'tb_sd_minus_2' => 96.2,
                'tb_sd_minus_1' => 100.6,
                'tb_sd_median' => 105.0,
                'tb_sd_plus_1' => 109.5,
                'tb_sd_plus_2' => 113.9,
                'tb_sd_plus_3' => 118.3,
            ],
            [
                'id' => '53',
                'usia_bulan' => 52,
                'tb_sd_minus_3' => 92.4,
                'tb_sd_minus_2' => 96.7,
                'tb_sd_minus_1' => 101.1,
                'tb_sd_median' => 105.6,
                'tb_sd_plus_1' => 110.0,
                'tb_sd_plus_2' => 114.5,
                'tb_sd_plus_3' => 119.0,
            ],
            [
                'id' => '54',
                'usia_bulan' => 53,
                'tb_sd_minus_3' => 92.8,
                'tb_sd_minus_2' => 97.2,
                'tb_sd_minus_1' => 101.6,
                'tb_sd_median' => 106.1,
                'tb_sd_plus_1' => 110.6,
                'tb_sd_plus_2' => 115.1,
                'tb_sd_plus_3' => 119.6,
            ],
            [
                'id' => '55',
                'usia_bulan' => 54,
                'tb_sd_minus_3' => 93.3,
                'tb_sd_minus_2' => 97.7,
                'tb_sd_minus_1' => 102.1,
                'tb_sd_median' => 106.7,
                'tb_sd_plus_1' => 111.2,
                'tb_sd_plus_2' => 115.7,
                'tb_sd_plus_3' => 120.3,
            ],
            [
                'id' => '56',
                'usia_bulan' => 55,
                'tb_sd_minus_3' => 93.7,
                'tb_sd_minus_2' => 98.1,
                'tb_sd_minus_1' => 102.6,
                'tb_sd_median' => 107.2,
                'tb_sd_plus_1' => 111.7,
                'tb_sd_plus_2' => 116.3,
                'tb_sd_plus_3' => 120.9,
            ],
            [
                'id' => '57',
                'usia_bulan' => 56,
                'tb_sd_minus_3' => 94.2,
                'tb_sd_minus_2' => 98.6,
                'tb_sd_minus_1' => 103.1,
                'tb_sd_median' => 107.7,
                'tb_sd_plus_1' => 112.3,
                'tb_sd_plus_2' => 116.9,
                'tb_sd_plus_3' => 121.5,
            ],
            [
                'id' => '58',
                'usia_bulan' => 57,
                'tb_sd_minus_3' => 94.6,
                'tb_sd_minus_2' => 99.1,
                'tb_sd_minus_1' => 103.6,
                'tb_sd_median' => 108.3,
                'tb_sd_plus_1' => 112.9,
                'tb_sd_plus_2' => 117.5,
                'tb_sd_plus_3' => 122.1,
            ],
            [
                'id' => '59',
                'usia_bulan' => 58,
                'tb_sd_minus_3' => 95.1,
                'tb_sd_minus_2' => 99.6,
                'tb_sd_minus_1' => 104.1,
                'tb_sd_median' => 108.8,
                'tb_sd_plus_1' => 113.4,
                'tb_sd_plus_2' => 118.1,
                'tb_sd_plus_3' => 122.7,
            ],
            [
                'id' => '60',
                'usia_bulan' => 59,
                'tb_sd_minus_3' => 95.5,
                'tb_sd_minus_2' => 100.0,
                'tb_sd_minus_1' => 104.6,
                'tb_sd_median' => 109.3,
                'tb_sd_plus_1' => 114.0,
                'tb_sd_plus_2' => 118.7,
                'tb_sd_plus_3' => 123.3,
            ],
            [
                'id' => '61',
                'usia_bulan' => 60,
                'tb_sd_minus_3' => 96.0,
                'tb_sd_minus_2' => 100.5,
                'tb_sd_minus_1' => 105.1,
                'tb_sd_median' => 109.9,
                'tb_sd_plus_1' => 114.6,
                'tb_sd_plus_2' => 119.2,
                'tb_sd_plus_3' => 123.9,
            ]
        ];

        DB::table('standar_antropometri_perempuan')->insert($data);
    }
}
