<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StandarAntopometriLakiSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id' => '1',
                'usia_bulan' => 0,
                'tb_sd_minus_3' => 44.2,
                'tb_sd_minus_2' => 46.1,
                'tb_sd_minus_1' => 48.0,
                'tb_sd_median' => 49.9,
                'tb_sd_plus_1' => 51.8,
                'tb_sd_plus_2' => 53.7,
                'tb_sd_plus_3' => 55.6,
            ],
            [
                'id' => '2',
                'usia_bulan' => 1,
                'tb_sd_minus_3' => 48.9,
                'tb_sd_minus_2' => 50.8,
                'tb_sd_minus_1' => 52.8,
                'tb_sd_median' => 54.7,
                'tb_sd_plus_1' => 56.7,
                'tb_sd_plus_2' => 58.6,
                'tb_sd_plus_3' => 60.6,
            ],
            [
                'id' => '3',
                'usia_bulan' => 2,
                'tb_sd_minus_3' => 52.4,
                'tb_sd_minus_2' => 54.4,
                'tb_sd_minus_1' => 56.4,
                'tb_sd_median' => 58.4,
                'tb_sd_plus_1' => 60.4,
                'tb_sd_plus_2' => 62.4,
                'tb_sd_plus_3' => 64.4,
            ],
            [
                'id' => '4',
                'usia_bulan' => 3,
                'tb_sd_minus_3' => 55.3,
                'tb_sd_minus_2' => 57.3,
                'tb_sd_minus_1' => 59.4,
                'tb_sd_median' => 61.4,
                'tb_sd_plus_1' => 63.5,
                'tb_sd_plus_2' => 65.5,
                'tb_sd_plus_3' => 67.6,
            ],
            [
                'id' => '5',
                'usia_bulan' => 4,
                'tb_sd_minus_3' => 57.6,
                'tb_sd_minus_2' => 59.7,
                'tb_sd_minus_1' => 61.8,
                'tb_sd_median' => 63.9,
                'tb_sd_plus_1' => 66.0,
                'tb_sd_plus_2' => 68.0,
                'tb_sd_plus_3' => 70.1,
            ],
            [
                'id' => '6',
                'usia_bulan' => 5,
                'tb_sd_minus_3' => 59.6,
                'tb_sd_minus_2' => 61.7,
                'tb_sd_minus_1' => 63.8,
                'tb_sd_median' => 65.9,
                'tb_sd_plus_1' => 68.0,
                'tb_sd_plus_2' => 70.1,
                'tb_sd_plus_3' => 72.2,
            ],
            [
                'id' => '7',
                'usia_bulan' => 6,
                'tb_sd_minus_3' => 61.2,
                'tb_sd_minus_2' => 63.3,
                'tb_sd_minus_1' => 65.5,
                'tb_sd_median' => 67.6,
                'tb_sd_plus_1' => 69.8,
                'tb_sd_plus_2' => 71.9,
                'tb_sd_plus_3' => 74.0,
            ],
            [
                'id' => '8',
                'usia_bulan' => 7,
                'tb_sd_minus_3' => 62.7,
                'tb_sd_minus_2' => 64.8,
                'tb_sd_minus_1' => 67.0,
                'tb_sd_median' => 69.2,
                'tb_sd_plus_1' => 71.3,
                'tb_sd_plus_2' => 73.5,
                'tb_sd_plus_3' => 75.7,
            ],
            [
                'id' => '9',
                'usia_bulan' => 8,
                'tb_sd_minus_3' => 64.0,
                'tb_sd_minus_2' => 66.2,
                'tb_sd_minus_1' => 68.4,
                'tb_sd_median' => 70.6,
                'tb_sd_plus_1' => 72.8,
                'tb_sd_plus_2' => 75.0,
                'tb_sd_plus_3' => 77.2,
            ],
            [
                'id' => '10',
                'usia_bulan' => 9,
                'tb_sd_minus_3' => 65.2,
                'tb_sd_minus_2' => 67.5,
                'tb_sd_minus_1' => 69.7,
                'tb_sd_median' => 72.0,
                'tb_sd_plus_1' => 74.2,
                'tb_sd_plus_2' => 76.5,
                'tb_sd_plus_3' => 78.7,
            ],
            [
                'id' => '11',
                'usia_bulan' => 10,
                'tb_sd_minus_3' => 66.4,
                'tb_sd_minus_2' => 68.7,
                'tb_sd_minus_1' => 71.0,
                'tb_sd_median' => 73.3,
                'tb_sd_plus_1' => 75.6,
                'tb_sd_plus_2' => 77.9,
                'tb_sd_plus_3' => 80.1,
            ],
            [
                'id' => '12',
                'usia_bulan' => 11,
                'tb_sd_minus_3' => 67.6,
                'tb_sd_minus_2' => 69.9,
                'tb_sd_minus_1' => 72.2,
                'tb_sd_median' => 74.5,
                'tb_sd_plus_1' => 76.9,
                'tb_sd_plus_2' => 79.2,
                'tb_sd_plus_3' => 81.5,
            ],
            [
                'id' => '13',
                'usia_bulan' => 12,
                'tb_sd_minus_3' => 68.6,
                'tb_sd_minus_2' => 71.0,
                'tb_sd_minus_1' => 73.4,
                'tb_sd_median' => 75.7,
                'tb_sd_plus_1' => 78.1,
                'tb_sd_plus_2' => 80.5,
                'tb_sd_plus_3' => 82.9,
            ],
            [
                'id' => '14',
                'usia_bulan' => 13,
                'tb_sd_minus_3' => 69.6,
                'tb_sd_minus_2' => 72.1,
                'tb_sd_minus_1' => 74.5,
                'tb_sd_median' => 76.9,
                'tb_sd_plus_1' => 79.3,
                'tb_sd_plus_2' => 81.8,
                'tb_sd_plus_3' => 84.2,
            ],
            [
                'id' => '15',
                'usia_bulan' => 14,
                'tb_sd_minus_3' => 70.6,
                'tb_sd_minus_2' => 73.1,
                'tb_sd_minus_1' => 75.6,
                'tb_sd_median' => 78.0,
                'tb_sd_plus_1' => 80.5,
                'tb_sd_plus_2' => 83.0,
                'tb_sd_plus_3' => 85.5,
            ],
            [
                'id' => '16',
                'usia_bulan' => 15,
                'tb_sd_minus_3' => 71.6,
                'tb_sd_minus_2' => 74.1,
                'tb_sd_minus_1' => 76.6,
                'tb_sd_median' => 79.1,
                'tb_sd_plus_1' => 81.7,
                'tb_sd_plus_2' => 84.2,
                'tb_sd_plus_3' => 86.7,
            ],
            [
                'id' => '17',
                'usia_bulan' => 16,
                'tb_sd_minus_3' => 72.5,
                'tb_sd_minus_2' => 75.0,
                'tb_sd_minus_1' => 77.6,
                'tb_sd_median' => 80.2,
                'tb_sd_plus_1' => 82.8,
                'tb_sd_plus_2' => 85.4,
                'tb_sd_plus_3' => 88.0,
            ],
            [
                'id' => '18',
                'usia_bulan' => 17,
                'tb_sd_minus_3' => 73.3,
                'tb_sd_minus_2' => 76.0,
                'tb_sd_minus_1' => 78.6,
                'tb_sd_median' => 81.2,
                'tb_sd_plus_1' => 83.9,
                'tb_sd_plus_2' => 86.5,
                'tb_sd_plus_3' => 89.2,
            ],
            [
                'id' => '19',
                'usia_bulan' => 18,
                'tb_sd_minus_3' => 74.2,
                'tb_sd_minus_2' => 76.9,
                'tb_sd_minus_1' => 79.6,
                'tb_sd_median' => 82.3,
                'tb_sd_plus_1' => 85.0,
                'tb_sd_plus_2' => 87.7,
                'tb_sd_plus_3' => 90.4,
            ],
            [
                'id' => '20',
                'usia_bulan' => 19,
                'tb_sd_minus_3' => 75.0,
                'tb_sd_minus_2' => 77.7,
                'tb_sd_minus_1' => 80.5,
                'tb_sd_median' => 83.2,
                'tb_sd_plus_1' => 86.0,
                'tb_sd_plus_2' => 88.8,
                'tb_sd_plus_3' => 91.5,
            ],
            [
                'id' => '21',
                'usia_bulan' => 20,
                'tb_sd_minus_3' => 75.8,
                'tb_sd_minus_2' => 78.6,
                'tb_sd_minus_1' => 81.4,
                'tb_sd_median' => 84.2,
                'tb_sd_plus_1' => 87.0,
                'tb_sd_plus_2' => 89.8,
                'tb_sd_plus_3' => 92.6,
            ],
            [
                'id' => '22',
                'usia_bulan' => 21,
                'tb_sd_minus_3' => 76.5,
                'tb_sd_minus_2' => 79.4,
                'tb_sd_minus_1' => 82.3,
                'tb_sd_median' => 85.1,
                'tb_sd_plus_1' => 88.0,
                'tb_sd_plus_2' => 90.9,
                'tb_sd_plus_3' => 93.8,
            ],
            [
                'id' => '23',
                'usia_bulan' => 22,
                'tb_sd_minus_3' => 77.2,
                'tb_sd_minus_2' => 80.2,
                'tb_sd_minus_1' => 83.1,
                'tb_sd_median' => 86.0,
                'tb_sd_plus_1' => 89.0,
                'tb_sd_plus_2' => 91.9,
                'tb_sd_plus_3' => 94.9,
            ],
            [
                'id' => '24',
                'usia_bulan' => 23,
                'tb_sd_minus_3' => 78.0,
                'tb_sd_minus_2' => 81.0,
                'tb_sd_minus_1' => 83.9,
                'tb_sd_median' => 86.9,
                'tb_sd_plus_1' => 89.9,
                'tb_sd_plus_2' => 92.9,
                'tb_sd_plus_3' => 95.9,
            ],
            [
                'id' => '25',
                'usia_bulan' => 24,
                'tb_sd_minus_3' => 78.7,
                'tb_sd_minus_2' => 81.7,
                'tb_sd_minus_1' => 84.8,
                'tb_sd_median' => 87.8,
                'tb_sd_plus_1' => 90.9,
                'tb_sd_plus_2' => 93.9,
                'tb_sd_plus_3' => 97.0,
            ],
            [
                'id' => '26', 
                'usia_bulan' => 25,
                'tb_sd_minus_3' => 79.4,
                'tb_sd_minus_2' => 82.5,
                'tb_sd_minus_1' => 85.6,
                'tb_sd_median' => 88.7,
                'tb_sd_plus_1' => 91.8,
                'tb_sd_plus_2' => 94.9,
                'tb_sd_plus_3' => 98.0,
            ],
            [
                'id' => '27',
                'usia_bulan' => 26,
                'tb_sd_minus_3' => 80.1,
                'tb_sd_minus_2' => 83.2,
                'tb_sd_minus_1' => 86.4,
                'tb_sd_median' => 89.6,
                'tb_sd_plus_1' => 92.7,
                'tb_sd_plus_2' => 95.9,
                'tb_sd_plus_3' => 99.0,
            ],
            [
                'id' => '28',
                'usia_bulan' => 27,
                'tb_sd_minus_3' => 80.8,
                'tb_sd_minus_2' => 83.9,
                'tb_sd_minus_1' => 87.1,
                'tb_sd_median' => 90.4,
                'tb_sd_plus_1' => 93.6,
                'tb_sd_plus_2' => 96.9,
                'tb_sd_plus_3' => 100.1,
            ],
            [
                'id' => '29',
                'usia_bulan' => 28,
                'tb_sd_minus_3' => 81.5,
                'tb_sd_minus_2' => 84.6,
                'tb_sd_minus_1' => 87.9,
                'tb_sd_median' => 91.2,
                'tb_sd_plus_1' => 94.4,
                'tb_sd_plus_2' => 97.7,
                'tb_sd_plus_3' => 101.0,
            ],
            [
                'id' => '30',
                'usia_bulan' => 29,
                'tb_sd_minus_3' => 82.1,
                'tb_sd_minus_2' => 85.3,
                'tb_sd_minus_1' => 88.6,
                'tb_sd_median' => 91.9,
                'tb_sd_plus_1' => 95.2,
                'tb_sd_plus_2' => 98.6,
                'tb_sd_plus_3' => 101.9,
            ],
            [
                'id' => '31',
                'usia_bulan' => 30,
                'tb_sd_minus_3' => 82.7,
                'tb_sd_minus_2' => 85.9,
                'tb_sd_minus_1' => 89.3,
                'tb_sd_median' => 92.7,
                'tb_sd_plus_1' => 96.1,
                'tb_sd_plus_2' => 99.4,
                'tb_sd_plus_3' => 102.8,
            ],
            [
                'id' => '32',
                'usia_bulan' => 31,
                'tb_sd_minus_3' => 83.3,
                'tb_sd_minus_2' => 86.5,
                'tb_sd_minus_1' => 89.9,
                'tb_sd_median' => 93.4,
                'tb_sd_plus_1' => 96.9,
                'tb_sd_plus_2' => 100.3,
                'tb_sd_plus_3' => 103.7,
            ],
            [
                'id' => '33',
                'usia_bulan' => 32,
                'tb_sd_minus_3' => 83.8,
                'tb_sd_minus_2' => 87.1,
                'tb_sd_minus_1' => 90.6,
                'tb_sd_median' => 94.1,
                'tb_sd_plus_1' => 97.6,
                'tb_sd_plus_2' => 101.1,
                'tb_sd_plus_3' => 104.6,
            ],
            [
                'id' => '34',
                'usia_bulan' => 33,
                'tb_sd_minus_3' => 84.4,
                'tb_sd_minus_2' => 87.7,
                'tb_sd_minus_1' => 91.2,
                'tb_sd_median' => 94.8,
                'tb_sd_plus_1' => 98.4,
                'tb_sd_plus_2' => 101.9,
                'tb_sd_plus_3' => 105.4,
            ],
            [
                'id' => '35',
                'usia_bulan' => 34,
                'tb_sd_minus_3' => 85.0,
                'tb_sd_minus_2' => 88.3,
                'tb_sd_minus_1' => 91.9,
                'tb_sd_median' => 95.4,
                'tb_sd_plus_1' => 99.0,
                'tb_sd_plus_2' => 102.6,
                'tb_sd_plus_3' => 106.2,
            ],
            [
                'id' => '36',
                'usia_bulan' => 35,
                'tb_sd_minus_3' => 85.5,
                'tb_sd_minus_2' => 88.9,
                'tb_sd_minus_1' => 92.5,
                'tb_sd_median' => 96.1,
                'tb_sd_plus_1' => 99.7,
                'tb_sd_plus_2' => 103.3,
                'tb_sd_plus_3' => 107.0,
            ],
            [
                'id' => '37',
                'usia_bulan' => 36,
                'tb_sd_minus_3' => 86.0,
                'tb_sd_minus_2' => 89.4,
                'tb_sd_minus_1' => 93.1,
                'tb_sd_median' => 96.7,
                'tb_sd_plus_1' => 100.4,
                'tb_sd_plus_2' => 104.0,
                'tb_sd_plus_3' => 107.7,
            ],
            [
                'id' => '38',
                'usia_bulan' => 37,
                'tb_sd_minus_3' => 86.5,
                'tb_sd_minus_2' => 90.0,
                'tb_sd_minus_1' => 93.6,
                'tb_sd_median' => 97.4,
                'tb_sd_plus_1' => 101.1,
                'tb_sd_plus_2' => 104.7,
                'tb_sd_plus_3' => 108.4,
            ],
            [
                'id' => '39',
                'usia_bulan' => 38,
                'tb_sd_minus_3' => 87.0,
                'tb_sd_minus_2' => 90.5,
                'tb_sd_minus_1' => 94.2,
                'tb_sd_median' => 98.0,
                'tb_sd_plus_1' => 101.7,
                'tb_sd_plus_2' => 105.4,
                'tb_sd_plus_3' => 109.1,
            ],
            [
                'id' => '40',
                'usia_bulan' => 39,
                'tb_sd_minus_3' => 87.5,
                'tb_sd_minus_2' => 91.0,
                'tb_sd_minus_1' => 94.7,
                'tb_sd_median' => 98.6,
                'tb_sd_plus_1' => 102.4,
                'tb_sd_plus_2' => 106.1,
                'tb_sd_plus_3' => 109.8,
            ],
            [
                'id' => '41',
                'usia_bulan' => 40,
                'tb_sd_minus_3' => 88.0,
                'tb_sd_minus_2' => 91.5,
                'tb_sd_minus_1' => 95.3,
                'tb_sd_median' => 99.2,
                'tb_sd_plus_1' => 103.0,
                'tb_sd_plus_2' => 106.8,
                'tb_sd_plus_3' => 110.5,
            ],
            [
                'id' => '42',
                'usia_bulan' => 41,
                'tb_sd_minus_3' => 88.4,
                'tb_sd_minus_2' => 92.0,
                'tb_sd_minus_1' => 95.8,
                'tb_sd_median' => 99.7,
                'tb_sd_plus_1' => 103.6,
                'tb_sd_plus_2' => 107.4,
                'tb_sd_plus_3' => 111.2,
            ],
            [
                'id' => '43',
                'usia_bulan' => 42,
                'tb_sd_minus_3' => 88.9,
                'tb_sd_minus_2' => 92.5,
                'tb_sd_minus_1' => 96.4,
                'tb_sd_median' => 100.3,
                'tb_sd_plus_1' => 104.2,
                'tb_sd_plus_2' => 108.1,
                'tb_sd_plus_3' => 111.9,
            ],
            [
                'id' => '44',
                'usia_bulan' => 43,
                'tb_sd_minus_3' => 89.4,
                'tb_sd_minus_2' => 93.0,
                'tb_sd_minus_1' => 96.9,
                'tb_sd_median' => 100.9,
                'tb_sd_plus_1' => 104.8,
                'tb_sd_plus_2' => 108.7,
                'tb_sd_plus_3' => 112.6,
            ],
            [
                'id' => '45',
                'usia_bulan' => 44,
                'tb_sd_minus_3' => 89.8,
                'tb_sd_minus_2' => 93.4,
                'tb_sd_minus_1' => 97.4,
                'tb_sd_median' => 101.4,
                'tb_sd_plus_1' => 105.4,
                'tb_sd_plus_2' => 109.3,
                'tb_sd_plus_3' => 113.3,
            ],
            [
                'id' => '46',
                'usia_bulan' => 45,
                'tb_sd_minus_3' => 90.3,
                'tb_sd_minus_2' => 93.9,
                'tb_sd_minus_1' => 97.9,
                'tb_sd_median' => 102.0,
                'tb_sd_plus_1' => 106.0,
                'tb_sd_plus_2' => 110.0,
                'tb_sd_plus_3' => 114.0,
            ],
            [
                'id' => '47',
                'usia_bulan' => 46,
                'tb_sd_minus_3' => 90.7,
                'tb_sd_minus_2' => 94.4,
                'tb_sd_minus_1' => 98.4,
                'tb_sd_median' => 102.5,
                'tb_sd_plus_1' => 106.6,
                'tb_sd_plus_2' => 110.6,
                'tb_sd_plus_3' => 114.6,
            ],
            [
                'id' => '48',
                'usia_bulan' => 47,
                'tb_sd_minus_3' => 91.2,
                'tb_sd_minus_2' => 94.9,
                'tb_sd_minus_1' => 98.9,
                'tb_sd_median' => 103.0,
                'tb_sd_plus_1' => 107.1,
                'tb_sd_plus_2' => 111.2,
                'tb_sd_plus_3' => 115.3,
            ],
            [
                'id' => '49',
                'usia_bulan' => 48,
                'tb_sd_minus_3' => 91.6,
                'tb_sd_minus_2' => 95.4,
                'tb_sd_minus_1' => 99.4,
                'tb_sd_median' => 103.5,
                'tb_sd_plus_1' => 107.7,
                'tb_sd_plus_2' => 111.8,
                'tb_sd_plus_3' => 115.9,
            ],
            [
                'id' => '50',
                'usia_bulan' => 49,
                'tb_sd_minus_3' => 92.1,
                'tb_sd_minus_2' => 95.9,
                'tb_sd_minus_1' => 99.9,
                'tb_sd_median' => 104.0,
                'tb_sd_plus_1' => 108.2,
                'tb_sd_plus_2' => 112.4,
                'tb_sd_plus_3' => 116.6,
            ],
            [
                'id' => '51',
                'usia_bulan' => 50,
                'tb_sd_minus_3' => 92.5,
                'tb_sd_minus_2' => 96.4,
                'tb_sd_minus_1' => 100.4,
                'tb_sd_median' => 104.5,
                'tb_sd_plus_1' => 108.8,
                'tb_sd_plus_2' => 113.0,
                'tb_sd_plus_3' => 117.2,
            ],
            [
                'id' => '52',
                'usia_bulan' => 51,
                'tb_sd_minus_3' => 93.0,
                'tb_sd_minus_2' => 96.9,
                'tb_sd_minus_1' => 100.9,
                'tb_sd_median' => 105.0,
                'tb_sd_plus_1' => 109.3,
                'tb_sd_plus_2' => 113.6,
                'tb_sd_plus_3' => 117.9,
            ],
            [
                'id' => '53',
                'usia_bulan' => 52,
                'tb_sd_minus_3' => 93.4,
                'tb_sd_minus_2' => 97.4,
                'tb_sd_minus_1' => 101.4,
                'tb_sd_median' => 105.6,
                'tb_sd_plus_1' => 109.9,
                'tb_sd_plus_2' => 114.2,
                'tb_sd_plus_3' => 118.5,
            ],
            [
                'id' => '54',
                'usia_bulan' => 53,
                'tb_sd_minus_3' => 93.9,
                'tb_sd_minus_2' => 97.9,
                'tb_sd_minus_1' => 102.0,
                'tb_sd_median' => 106.1,
                'tb_sd_plus_1' => 110.4,
                'tb_sd_plus_2' => 114.8,
                'tb_sd_plus_3' => 119.2,
            ],
            [
                'id' => '55',
                'usia_bulan' => 54,
                'tb_sd_minus_3' => 94.3,
                'tb_sd_minus_2' => 98.4,
                'tb_sd_minus_1' => 102.5,
                'tb_sd_median' => 106.7,
                'tb_sd_plus_1' => 111.0,
                'tb_sd_plus_2' => 115.4,
                'tb_sd_plus_3' => 119.8,
            ],
            [
                'id' => '56',
                'usia_bulan' => 55,
                'tb_sd_minus_3' => 94.7,
                'tb_sd_minus_2' => 98.9,
                'tb_sd_minus_1' => 103.0,
                'tb_sd_median' => 107.2,
                'tb_sd_plus_1' => 111.5,
                'tb_sd_plus_2' => 116.0,
                'tb_sd_plus_3' => 120.4,
            ],
            [
                'id' => '57',
                'usia_bulan' => 56,
                'tb_sd_minus_3' => 95.2,
                'tb_sd_minus_2' => 99.4,
                'tb_sd_minus_1' => 103.5,
                'tb_sd_median' => 107.8,
                'tb_sd_plus_1' => 112.1,
                'tb_sd_plus_2' => 116.6,
                'tb_sd_plus_3' => 121.1,
            ],
            [
                'id' => '58',
                'usia_bulan' => 57,
                'tb_sd_minus_3' => 95.6,
                'tb_sd_minus_2' => 99.9,
                'tb_sd_minus_1' => 104.0,
                'tb_sd_median' => 108.3,
                'tb_sd_plus_1' => 112.7,
                'tb_sd_plus_2' => 117.1,
                'tb_sd_plus_3' => 121.7,
            ],
            [
                'id' => '59',
                'usia_bulan' => 58,
                'tb_sd_minus_3' => 96.1,
                'tb_sd_minus_2' => 100.4,
                'tb_sd_minus_1' => 104.5,
                'tb_sd_median' => 108.9,
                'tb_sd_plus_1' => 113.3,
                'tb_sd_plus_2' => 117.7,
                'tb_sd_plus_3' => 122.3,
            ],
            [
                'id' => '60',
                'usia_bulan' => 59,
                'tb_sd_minus_3' => 96.5,
                'tb_sd_minus_2' => 100.9,
                'tb_sd_minus_1' => 105.0,
                'tb_sd_median' => 109.4,
                'tb_sd_plus_1' => 113.8,
                'tb_sd_plus_2' => 118.3,
                'tb_sd_plus_3' => 122.9,
            ],
            [
                'id' => '61',
                'usia_bulan' => 60,
                'tb_sd_minus_3' => 97.0,
                'tb_sd_minus_2' => 101.4,
                'tb_sd_minus_1' => 105.6,
                'tb_sd_median' => 110.0,
                'tb_sd_plus_1' => 114.4,
                'tb_sd_plus_2' => 118.9,
                'tb_sd_plus_3' => 123.5,
            ]
        ];

        DB::table('standar_antropometri_laki')->insert($data);
    }
}